spring:
  application:
    name: dreamweaver-spring-cloud-service-admin
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8801

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/
